version: "3.9"

services:
  app:
    container_name: app-pro-container
    build: .
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_USER: meuuser
      DB_PASSWORD: minhasenha
      DB_NAME: meubanco
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: meuuser
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meubanco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meuuser"]
      interval: 10s
      timeout: 5s
      retries: 5

