apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-role
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "deployments", "configmaps", "secrets"]
    verbs: ["get", "list", "apply", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-binding
subjects:
  - kind: ServiceAccount
    name: github-actions
roleRef:
  kind: Role
  name: deploy-role
  apiGroup: rbac.authorization.k8s.io

