name: CI - Meu App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Subir containers
        run: docker compose up -d --build

      - name: Aguardar aplicação ficar saudável
        run: |
          echo "Aguardando healthcheck do container..."
          for i in {1..15}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' meu-app-app || true)
            echo "Status: $STATUS"
            if [ "$STATUS" = "healthy" ]; then
              echo "Aplicação saudável!"
              exit 0
            fi
            sleep 4
          done
          echo "Aplicação não ficou saudável"
          docker compose logs
          exit 1

      - name: Garantir permissão dos scripts
        run: chmod +x scripts/*.sh

      - name: Executar testes
        run: ./scripts/test.sh

      - name: Derrubar containers
        if: always()
        run: docker compose down

