name: CI - Meu App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Subir containers
        run: docker compose up -d --build

      - name: Aguardar app ficar saudável
        run: |
          for i in {1..20}; do
            STATUS=$(docker inspect --format='{{.State.Health.Status}}' app-pro-container)
            if [ "$STATUS" = "healthy" ]; then
              echo "✅ App saudável"
              exit 0
            fi
            echo "⏳ Aguardando app..."
            sleep 3
          done
          echo "❌ App não ficou saudável"
          docker compose logs
          exit 1

      - name: Derrubar containers
        if: always()
        run: docker compose down

