name: CI - Meu App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Subir containers
        run: docker compose up -d --build

      - name: Aguardar serviços
        run: sleep 30

      - name: Garantir permissão scripts
        run: chmod +x scripts/*.sh

      - name: Executar testes
        run: ./scripts/test.sh

      - name: Derrubar containers
        if: always()
        run: docker compose down

